/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language, BusinessProfile, Transaction, MandiPrice, WeatherData, EMIDetail, AlertCard } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളம்' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'as', name: 'Assamese', nativeName: 'ଅସମୀୟା' }
];

export const BUSINESS_PROFILES: BusinessProfile[] = [
  {
    id: 'ramesh_dairy',
    ownerName: 'Ramesh Patel',
    businessName: 'Patel Dairy & Milk Collection',
    businessType: 'Dairy Farm',
    village: 'Kalyanpur',
    district: 'Anand',
    preferredLanguage: 'gu',
    loanDetails: 'SBI Agri-Infrastructure Loan: ₹1,50,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: true, weather: true },
    cashRunwayDays: 45,
    confidenceScore: 92,
    healthScore: 84,
    initialCashBuffer: 20000
  },
  {
    id: 'sunita_kirana',
    ownerName: 'Sunita Sharma',
    businessName: 'Sharma Kirana & General Store',
    businessType: 'Kirana Store',
    village: 'Rampur',
    district: 'Patna',
    preferredLanguage: 'hi',
    loanDetails: 'MUDRA Shishu Loan: ₹28,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: false, weather: true },
    cashRunwayDays: 18,
    confidenceScore: 88,
    healthScore: 62,
    initialCashBuffer: 8000
  },
  {
    id: 'gopi_poultry',
    ownerName: 'Gopi Krishna',
    businessName: 'Sri Krishna Poultry Farm',
    businessType: 'Poultry Farm',
    village: 'Guntakal',
    district: 'Anantapur',
    preferredLanguage: 'te',
    loanDetails: 'NABARD Poultry Scheme: ₹2,10,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: true, weather: true },
    cashRunwayDays: 75,
    confidenceScore: 95,
    healthScore: 91,
    initialCashBuffer: 32000
  },
  {
    id: 'anil_tailor',
    ownerName: 'Anil Verma',
    businessName: 'Verma Tailoring & Boutique',
    businessType: 'Tailoring Shop',
    village: 'Pipariya',
    district: 'Indore',
    preferredLanguage: 'hi',
    loanDetails: 'MUDRA Kishor Loan: ₹85,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: false, weather: true },
    cashRunwayDays: 50,
    confidenceScore: 86,
    healthScore: 86,
    initialCashBuffer: 12000
  },
  {
    id: 'radha_weaving',
    ownerName: 'Radha Subramaniam',
    businessName: 'Laxmi Handloom Weavers',
    businessType: 'Handloom Weaving',
    village: 'Elampillai',
    district: 'Salem',
    preferredLanguage: 'ta',
    loanDetails: 'TNHDC Weaver Loan: ₹60,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: false, mandi: true, weather: true },
    cashRunwayDays: 38,
    confidenceScore: 78,
    healthScore: 78,
    initialCashBuffer: 15000
  },
  {
    id: 'mohan_tea',
    ownerName: 'Mohan Joshi',
    businessName: 'Joshi Tea Stall & Snacks',
    businessType: 'Tea Stall',
    village: 'Loni Kalbhor',
    district: 'Pune',
    preferredLanguage: 'mr',
    loanDetails: 'Co-operative Bank Loan: ₹20,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: false, weather: true },
    cashRunwayDays: 22,
    confidenceScore: 68,
    healthScore: 68,
    initialCashBuffer: 6000
  },
  {
    id: 'kamla_handicraft',
    ownerName: 'Kamla Devi',
    businessName: 'Mewar Wooden Toys & Art',
    businessType: 'Wooden Handicrafts',
    village: 'Shilpgram',
    district: 'Udaipur',
    preferredLanguage: 'hi',
    loanDetails: 'SIDBI Micro-Finance: ₹45,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: true, weather: false },
    cashRunwayDays: 42,
    confidenceScore: 82,
    healthScore: 82,
    initialCashBuffer: 14000
  },
  {
    id: 'vikram_fertilizer',
    ownerName: 'Vikram Singh',
    businessName: 'Singh Kisan Agri-Inputs',
    businessType: 'Agri-Input Store',
    village: 'Sahnewal',
    district: 'Ludhiana',
    preferredLanguage: 'pa',
    loanDetails: 'PFC Fertilizer Credit: ₹3,50,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: true, weather: true },
    cashRunwayDays: 90,
    confidenceScore: 94,
    healthScore: 94,
    initialCashBuffer: 50000
  },
  {
    id: 'savita_beauty',
    ownerName: 'Savita Patel',
    businessName: 'Savita Ladies Beauty Parlour',
    businessType: 'Beauty Parlour',
    village: 'Visnagar',
    district: 'Mehsana',
    preferredLanguage: 'gu',
    loanDetails: 'Dena Gujarat Gramin Bank: ₹25,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: false, weather: true },
    cashRunwayDays: 30,
    confidenceScore: 79,
    healthScore: 79,
    initialCashBuffer: 9000
  },
  {
    id: 'rajesh_repair',
    ownerName: 'Rajesh Goud',
    businessName: 'Sri Sai Mobile & Electronic Services',
    businessType: 'Electronics Repair',
    village: 'Hanamkonda',
    district: 'Warangal',
    preferredLanguage: 'te',
    loanDetails: 'MUDRA Shishu Loan: ₹15,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: false, weather: true },
    cashRunwayDays: 40,
    confidenceScore: 81,
    healthScore: 81,
    initialCashBuffer: 11000
  },
  {
    id: 'harish_pottery',
    ownerName: 'Harish Mohanty',
    businessName: 'Kalinga Clay Art & Pottery',
    businessType: 'Pottery Workshop',
    village: 'Balakati',
    district: 'Khurda',
    preferredLanguage: 'or',
    loanDetails: 'Khadi Gramodyog (KVIC): ₹35,000 remaining',
    upiLinked: false,
    smsPermission: true,
    consentSettings: { sms: true, upi: false, mandi: true, weather: true },
    cashRunwayDays: 25,
    confidenceScore: 71,
    healthScore: 71,
    initialCashBuffer: 7000
  },
  {
    id: 'fatima_bakery',
    ownerName: 'Fatima Bi',
    businessName: 'Fatima Home Bakery',
    businessType: 'Home Bakery',
    village: 'Malihabad',
    district: 'Lucknow',
    preferredLanguage: 'ur',
    loanDetails: 'Co-operative Mahila Bank: ₹30,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: false, weather: true },
    cashRunwayDays: 28,
    confidenceScore: 74,
    healthScore: 74,
    initialCashBuffer: 8000
  },
  {
    id: 'samir_carpenter',
    ownerName: 'Samir Das',
    businessName: 'Das Wooden Furniture Maker',
    businessType: 'Carpentry Shop',
    village: 'Katwa',
    district: 'Burdwan',
    preferredLanguage: 'bn',
    loanDetails: 'SBI Business Loan: ₹1,20,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: true, weather: false },
    cashRunwayDays: 55,
    confidenceScore: 88,
    healthScore: 88,
    initialCashBuffer: 25000
  },
  {
    id: 'dev_sweet',
    ownerName: 'Dev Dutt',
    businessName: 'Ganga Mishthan Bhandar',
    businessType: 'Sweet Shop',
    village: 'Sarnath',
    district: 'Varanasi',
    preferredLanguage: 'hi',
    loanDetails: 'Union Bank Loan: ₹80,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: true, weather: true },
    cashRunwayDays: 64,
    confidenceScore: 90,
    healthScore: 90,
    initialCashBuffer: 30000
  },
  {
    id: 'laxmi_fishery',
    ownerName: 'Laxmi Nair',
    businessName: 'Nair Fish Farming Pond',
    businessType: 'Inland Fishery',
    village: 'Angamaly',
    district: 'Ernakulam',
    preferredLanguage: 'ml',
    loanDetails: 'Kerala Fisheries Credit: ₹1,80,000 remaining',
    upiLinked: true,
    smsPermission: true,
    consentSettings: { sms: true, upi: true, mandi: true, weather: true },
    cashRunwayDays: 48,
    confidenceScore: 83,
    healthScore: 83,
    initialCashBuffer: 24000
  }
];


export const TRANSACTIONS: Transaction[] = [
  { id: 'tx_1', date: '2026-07-18', description: 'Milk Collection Payout (Amul)', category: 'Income', amount: 8400, source: 'UPI' },
  { id: 'tx_2', date: '2026-07-17', description: 'Animal Feed Purchase (Kapila Feed)', category: 'Expense', amount: 3200, source: 'UPI' },
  { id: 'tx_3', date: '2026-07-15', description: 'Veterinary Checkup & Medicines', category: 'Expense', amount: 1200, source: 'SMS' },
  { id: 'tx_4', date: '2026-07-12', description: 'Retail Milk Sales Cash', category: 'Income', amount: 4500, source: 'Cash' },
  { id: 'tx_5', date: '2026-07-10', description: 'HDFC Tractor Loan EMI', category: 'EMI', amount: 7500, source: 'SMS' },
  { id: 'tx_6', date: '2026-07-08', description: 'Electricity Bill - Pump & Barn', category: 'Expense', amount: 1800, source: 'SMS' },
  { id: 'tx_7', date: '2026-07-05', description: 'Fertilizer & Seeds subsidy', category: 'Income', amount: 2000, source: 'Bank' },
  { id: 'tx_8', date: '2026-07-02', description: 'Local Wholesale Supplier Pay', category: 'Expense', amount: 4800, source: 'UPI' },
  { id: 'tx_9', date: '2026-06-30', description: 'Dairy Milk Society Bonus', category: 'Income', amount: 5000, source: 'Bank' },
  { id: 'tx_10', date: '2026-06-28', description: 'Daily Milk Collection (Amul)', category: 'Income', amount: 8100, source: 'UPI' }
];

export const MANDI_PRICES: MandiPrice[] = [
  {
    id: 'm_1',
    commodity: 'Raw Milk (4.5% Fat)',
    currentPrice: 42,
    unit: 'Litre',
    yesterdayPrice: 44,
    trend: 'DOWN',
    weeklyTrend: [46, 45, 44.5, 44, 42],
    aiAdvice: 'HOLD',
    expectedTrend: 'Expected to drop further next week due to high seasonal supply. Consider processing into Paneer/Ghee to preserve value.',
    nearbyMarkets: [
      { marketName: 'Anand APMC', price: 42 },
      { marketName: 'Nadiad Mandi', price: 43.5 },
      { marketName: 'Vadodara Cooperatives', price: 41 }
    ]
  },
  {
    id: 'm_2',
    commodity: 'Wheat (Kalyan Sona)',
    currentPrice: 2450,
    unit: 'Quintal',
    yesterdayPrice: 2420,
    trend: 'UP',
    weeklyTrend: [2380, 2400, 2410, 2420, 2450],
    aiAdvice: 'SELL',
    expectedTrend: 'Strong post-harvest demand. Prices have hit a 30-day peak. Excellent time to liquidate current grain stock.',
    nearbyMarkets: [
      { marketName: 'Gondal APMC', price: 2450 },
      { marketName: 'Rajkot Market Yard', price: 2430 },
      { marketName: 'Morbi Mandi', price: 2465 }
    ]
  },
  {
    id: 'm_3',
    commodity: 'Green Gram / Moong',
    currentPrice: 7800,
    unit: 'Quintal',
    yesterdayPrice: 7800,
    trend: 'STABLE',
    weeklyTrend: [7750, 7800, 7800, 7800, 7800],
    aiAdvice: 'BUY LATER',
    expectedTrend: 'Steady arrivals from Southern states. Prices are stable but IMD rainfall warnings might disrupt logistics next week.',
    nearbyMarkets: [
      { marketName: 'Surat APMC', price: 7800 },
      { marketName: 'Mehsana Mandi', price: 7900 }
    ]
  },
  {
    id: 'm_4',
    commodity: 'Cotton (Shankar-6)',
    currentPrice: 6200,
    unit: 'Quintal',
    yesterdayPrice: 6300,
    trend: 'DOWN',
    weeklyTrend: [6500, 6420, 6350, 6300, 6200],
    aiAdvice: 'HOLD',
    expectedTrend: 'Global export slowdown causing drop. Hold stock for 15 days as state procurement starts shortly at MSP (₹6,620).',
    nearbyMarkets: [
      { marketName: 'Amreli APMC', price: 6200 },
      { marketName: 'Bodeli Market Yard', price: 6250 }
    ]
  }
];

export const WEATHER_DATA: WeatherData = {
  temp: 34,
  humidity: 78,
  rainfall: 'Scattered Showers (12mm)',
  windSpeed: '18 km/h',
  description: 'Hot & Humid with Light Evening Rain',
  icon: 'cloudy',
  forecast7Days: [
    { day: 'Sun', temp: 35, icon: 'sunny', impact: 'Normal milk collection.' },
    { day: 'Mon', temp: 36, icon: 'sunny', impact: 'High heat stress on cattle. Milk yield may drop by 10%.' },
    { day: 'Tue', temp: 37, icon: 'sunny', impact: 'Intense heatwave. Keep cattle indoors, supply electrolyte water.' },
    { day: 'Wed', temp: 32, icon: 'rainy', impact: 'Heavy rain. Transport logistics likely delayed. Cover feed storage.' },
    { day: 'Thu', temp: 30, icon: 'rainy', impact: 'Moderate showers. High humidity. Spray barns to prevent ticks.' },
    { day: 'Fri', temp: 31, icon: 'cloudy', impact: 'Cloudy, cooler temp. Feed intake will recover.' },
    { day: 'Sat', temp: 33, icon: 'sunny', impact: 'Sunny, normal operations.' }
  ],
  aiBusinessImpact: [
    'Heat wave expected Monday-Tuesday. Dairy yield likely to reduce by 1.5 litres per animal daily due to thermal stress.',
    'Heavy rain on Wednesday may block Kalyanpur rural link road. Amul tanker might arrive 3 hours late. Store milk in chiller early.',
    'High humidity levels increase risk of Mastitis infection. Maintain strict milking hygiene and dry bedding.'
  ]
};

export const EMI_DETAILS: EMIDetail[] = [
  {
    id: 'emi_1',
    lenderName: 'HDFC Bank Tractor Loan',
    amount: 7500,
    dueDate: '2026-07-26',
    daysRemaining: 8,
    riskStatus: 'YELLOW',
    cashAvailable: 6200,
    aiAdvice: [
      'You are short of ₹1,300 to clear the EMI automatically.',
      'Amul payment is due on 22nd July (Expected ₹8,200). You are fully SAFE if that arrives.',
      'Keep backup: Collect ₹1,500 pending credit from local tea shop owner today.'
    ]
  },
  {
    id: 'emi_2',
    lenderName: 'SBI Kisan Credit Card (KCC)',
    amount: 45000,
    dueDate: '2026-08-15',
    daysRemaining: 28,
    riskStatus: 'GREEN',
    cashAvailable: 52000,
    aiAdvice: [
      'KCC repayment is fully covered by your current liquid cash balance.',
      'No immediate cash stress predicted for August repayments.',
      'We recommend repaying 3 days early to boost your CIBIL score from 740 to 755.'
    ]
  }
];

export const ALERTS_LOG: AlertCard[] = [
  {
    id: 'a_1',
    type: 'cash',
    risk: 'YELLOW',
    title: 'Cash Runway Warning',
    description: 'Based on current milk yield drops and feed cost spikes, your cash runway will fall below ₹4,000 in 18 days. Consider deferring purchase of new milking buckets.',
    voiceAudioText: 'Aapki nakadi ka kharcha agle atharah dino mein badh sakta hai. Amul se bhugtan milte hi EMI jama karein aur naye bartan na khareedein.',
    date: 'Today, 08:30 AM'
  },
  {
    id: 'a_2',
    type: 'weather',
    risk: 'RED',
    title: 'Heatwave Alert (Thermal Cattle Stress)',
    description: 'Temperatures will touch 37°C on Monday. Dairy production predicted to drop by 12%. Keep cows under shed and mix salt/jaggery in drinking water.',
    voiceAudioText: 'Somvaar ko taapmaan saintees degree tak jayega. Dudh utpaadan baarah pratishat ghat sakta hai. Pashuon ko chhaon mein rakhein aur gur ka paani dein.',
    date: 'Yesterday, 04:15 PM'
  },
  {
    id: 'a_3',
    type: 'market',
    risk: 'YELLOW',
    title: 'Amul Milk fat rate drop prediction',
    description: 'Agmarknet prices indicate a seasonal 4% milk price dip in Gujarat next week. Sell extra milk society shares now to secure stable premium rates.',
    voiceAudioText: 'Agle hafte dudh ke fat ka rate chaar pratishat tak kam ho sakta hai. Apne amul shares ki bachat ka upayog karein.',
    date: '16 July 2026'
  },
  {
    id: 'a_4',
    type: 'emi',
    risk: 'GREEN',
    title: 'Tractor EMI safe route planned',
    description: 'Auto-debit for SBI EMI on 26th July is pre-allocated. Liquid cash in account is secure. Avoid any secondary loan inquiries this month.',
    voiceAudioText: 'Chhabis july ki tractor kist surakshit hai. Bank balance paryapt hai. Naya karj abhi na lein.',
    date: '15 July 2026'
  }
];

// Multilingual translations for core chatbot scenarios and interactive guide
export const CHATBOT_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    "monitoringUnit": "Monitoring Active Unit:",
    "villageCluster": "Village Cluster:",
    "districtJurisdiction": "District jurisdiction:",
    "primaryIndustry": "Primary Industry:",
    "aaConsentApi": "AA Consent API:",
    "creditConfidenceScore": "Credit Confidence Score:",
    "liveSyncConsole": "Live Data Sync Console",
    "verifyPassiveIngestion": "Verify Passive Ingestion & Offline Sync live on Atlas MongoDB",
    "ingestSmsAlerts": "1. Ingest passive SMS transaction alerts",
    "ingestSmsHelp": "Type or click a preset SMS transaction to simulate passive aggregator ingestion. Watch metrics dynamically recalculate.",
    "pasteSmsPlaceholder": "Paste raw SMS message from bank...",
    "ingestSmsBtn": "Ingest SMS",
    "offlineQueueLedger": "2. Offline Sync & Queue Ledger",
    "queuedRecords": "Queued Records:",
    "noQueuedOps": "No queued operations. System synchronized.",
    "forceOfflineSync": "Force Offline Sync Reconcile",
    "activeAdvisories": "16 transactions synced • 2 active advisories requiring attention.",
    "dialInCompanion": "Dial-In companion Call (English/Dialect)",
    "todaysAiAdvisories": "Today's AI Advisory Bulletins",
    "dynamicallyUpdated": "Dynamically Updated",
    "simulatedCashPredictions": "Simulated Cash Flow Predictions (90 Days)",
    "engineView": "Engine View →",
    "whatsDriving": "What's Driving This Forecast (Top 3 Factors):",
    "openPassbook": "Open Passbook →",
    "expandIndex": "Expand Index →",
    "dateCol": "Date",
    "descCol": "Description",
    "catCol": "Category",
    "amtCol": "Amount",
    "cropCol": "Commodity Crop",
    "rateCol": "Rate",
    "adviceCol": "Advice",
    "hold": "HOLD",
    "sell": "SELL",
    "buyNow": "BUY NOW",
    "buyLater": "BUY LATER",
    "rbiSyncTitle": "RBI Aggregator Data Permission Sync",
    "smsConsentDesc": "Extract debit/credit SMS alerts",
    "upiConsentDesc": "Merchant payments verification APIs",
    "imdConsentDesc": "Calculate cattle heat yields drop correlation",
    "viewFull": "View Full →",
    "viewFullDebt": "View Full AI Debt Strategy",
    "welcome": "Hello Ramesh! I am GramBot AI, your financial assistant. I understand your village, your farm, Amul, and IMD weather trends. How can I help you protect your business today?",
    "voiceText": "Listening...",
    "suggest1": "Can I pay my tractor EMI on 26th July?",
    "suggest2": "Why is my financial health Yellow today?",
    "suggest3": "How will Monday's heatwave affect my milk sales?",
    "suggest4": "What if dairy feed costs increase by 10%?",
    "reply1": "Yes, you can comfortably pay your ₹7,500 EMI on 26th July. Your forecasted cash on 26th is ₹14,400, supported by your upcoming milk societies payout of ₹8,200 on 22nd July. You are fully SAFE.",
    "reply2": "Your health is Yellow because feed costs increased by 15% this month, and predicted high temperatures next Monday (37°C) will likely cause a temporary 12% drop in milk production. We recommend saving ₹400 daily to remain safe.",
    "reply3": "Monday's heat of 37°C creates thermal stress for cattle. High-yielding Jersey cows will produce 1.5 - 2 Litres less milk per day. Overall daily revenue will drop by roughly ₹280. Supply cold water and salt to reduce this drop.",
    "reply4": "If feed costs rise by 10%, your daily expenses increase by ₹80. Your 30-day cash runway drops from 45 days to 38 days. To balance this, collect ₹1,500 pending milk dues from local shops immediately.",
    "feedback": "Did you understand this advice? (Speak 'Yes' or press thumbs up)",
    "offlineMsg": "Running offline. Your request is processed locally using GramPulse AI's offline model on your phone. No internet needed!",
    "fallback": "Understood. Our AI suggests keeping ₹2,500 cash reserves in liquid balance to handle upcoming rain disruptions. Tap 'Check Forecast' for more details.",
    "overviewPanel": "Overview Dashboard",
    "passbook": "Passbook",
    "userProfile": "Profile",
    "debtStrategy": "Debt Strategy",
    "governmentSchemes": "Gov. Schemes",
    "riskAnalysis": "Risk Analysis",
    "systemDiagnostics": "System Diagnostics",
    "syncStatus": "Sync Status",
    "liveSyncApi": "✓ Live API Sync",
    "logOutAccount": "Sign Out",
    "dataAsOf": "Data as of",
    "masterSynced": "Master Synced",
    "sinceLastChecked": "Since Last Checked",
    "quickActions": "Quick Actions:",
    "logTransaction": "Log Transaction",
    "viewFullForecast": "View Forecast",
    "registerLoanEmi": "Register Loan / EMI",
    "voiceCompanion": "Voice Companion",
    "financialHealthIndex": "Financial Health Index",
    "predictedCashRunway": "Predicted Cash Runway",
    "outstandingLoansEmi": "Outstanding Loan EMI",
    "climateThermalStress": "Climate Thermal Stress",
    "criticalRisk": "Critical Risk",
    "warningAlert": "Warning",
    "fullySafe": "Fully Safe",
    "safe": "Safe",
    "danger": "Danger",
    "warning": "Warning",
    "daysLeft": "Days",
    "recentAlertsTitle": "Recent Alerts",
    "logManualTxn": "Log Manual Transaction",
    "txDescription": "Transaction Description",
    "txCategory": "Category",
    "txAmount": "Amount",
    "txSource": "Source",
    "submitTxBtn": "Submit Transaction",
    "trackCustomMandi": "Track Custom Mandi Crop",
    "historicalComparison": "Historical Weather Comparison",
    "prepChecklist": "Weather Prep Checklist",
    "reportDisruption": "Report Weather Disruption",
    "exportBankCsv": "Export Bank CSV",
    "searchTransactions": "Search transactions...",
    "allCategories": "All Categories",
    "incomeOnly": "Income Only",
    "expenseOnly": "Expense Only",
    "duplicateDetectorActive": "✓ Duplicate Detector Active",
    "rbiConsentDashboard": "RBI Account Aggregator (AA) Consent Dashboard",
    "revokeAllAccess": "Revoke All Access",
    "dataAuditLog": "Cryptographic Data Access Audit Log (Last 5 attempts)",
    "creditConfidence": "Credit Confidence Score",
    "auditTrailTitle": "Field Verification Audit Trail",
    "debtStrategyDesc": "AI-driven cash-flow matching & repayment planning guidelines.",
    "refinancingChecklist": "Refinancing Docs Checklist",
    "refreshAnalysis": "Refresh Analysis",
    "analyzingObligations": "Analyzing debt obligations and cash flow...",
    "totalMonthlyEmi": "Total Monthly EMI",
    "acrossActiveLoans": "Across active loans",
    "dtiRatio": "Debt-To-Income (DTI)",
    "safeDtiZone": "✓ Safe DTI Zone",
    "moderateBurden": "⚠ Moderate Burden",
    "highRiskDti": "🔴 High Risk DTI",
    "totalOutstandingDebt": "Total Outstanding Debt",
    "principalRemaining": "Principal remaining",
    "priorityQueueTitle": "AI Recommended Repayment Priority Queue",
    "rankedByRisk": "Ranked by risk & penalty rate",
    "highPriorityCovered": "High Priority (Covered)",
    "urgentShortfall": "Urgent (Shortfall)",
    "activeStrategiesTitle": "Active Loan Strategies & Amortization",
    "onTimeTrackRecord": "✓ 12/12 On-Time",
    "amortizationBtn": "Amortization Schedule 📊",
    "emiMonth": "EMI / month",
    "cashAvailable": "Cash Available",
    "expectedIncoming": "Expected Incoming",
    "shortfall": "Shortfall",
    "surplus": "Surplus",
    "outstanding": "Outstanding",
    "aiStrategy": "AI Strategy",
    "registerNewLoan": "🏦 Register New Loan / EMI",
    "submitEmiSub": "Register active EMIs to view cash safety.",
    "lenderBankName": "Lender Bank Name",
    "bankPlaceholder": "e.g. SBI Agri Branch",
    "loanTypeCategory": "Loan Type / Category",
    "monthlyEmiAmount": "Monthly EMI Amount",
    "totalOutstandingLabel": "Total Outstanding Amount",
    "daysToDueDate": "Days to Due Date",
    "registerDebtBtn": "Register Debt",
    "repaymentGuidelines": "Repayment Guidelines",
    "welcomeBack": "Welcome back",
    "enterpriseDashboard": "Enterprise Dashboard",
    "scenarioForecastTitle": "Cash Flow Forecast & Scenarios",
    "mandiIntelTitle": "Mandi Market Intelligence",
    "passbookTitle": "Transaction Passbook",
    "weatherPortalTitle": "Weather Intelligence Portal",
    "schemesTitle": "Government Schemes & AI Recommendations",
    "profileMgmtTitle": "Business Profile Management",
    "rbiConsentTitle": "RBI Consent & Privacy Settings",
    "debtStrategyTitle": "AI Debt Strategy Advisory",
    "riskAnalysisTitle": "Business Risk Analysis",
    "interactivePredictions": "Forecast",
    "mandiPrices": "Mandi Prices",
    "weatherIntel": "Weather",
    "rbiConsent": "RBI Consent",
    "mandiConsentDesc": "Real-time market price data",
    "weatherConsentDesc": "IMD weather forecast data",
    "revokeAllAccessBtn": "Revoke All Access",
    "dataAuditTitle": "Cryptographic Data Access Audit (Last 5 attempts)",
    "registerBusiness": "Register New Micro-Enterprise",
    "ownerNameLabel": "Owner Name",
    "businessNameLabel": "Business Name",
    "businessTypeLabel": "Business Type",
    "villageLabel": "Village",
    "districtLabel": "District",
    "loanDetailsLabel": "Loan Details",
    "upiLinkedLabel": "UPI Linked",
    "smsPermLabel": "SMS Permission",
    "registerBtn": "Register Business",
    "aiConfidenceScore": "AI Confidence Score",
    "howItWorks": "How It Works",
    "redAdvice": "Risk: Your cash balance is under pressure from multiple factors. Avoid new purchases, collect pending dues from village shops, and consider micro-credit schemes.",
    "yellowAdvice": "Caution: Rising feed costs are pushing your cash balance toward the warning line. Avoid large expenses and monitor weather closely.",
    "greenAdvice": "Excellent: Your cash planning is very secure. You have sufficient funds to cover all EMIs and grow your business.",
  },
  hi: {
    "monitoringUnit": "सक्रिय इकाई:",
    "villageCluster": "गांव क्लस्टर:",
    "districtJurisdiction": "जिला क्षेत्र:",
    "primaryIndustry": "मुख्य उद्योग:",
    "aaConsentApi": "एए सहमति एपीआई:",
    "creditConfidenceScore": "क्रेडिट विश्वास स्कोर:",
    "liveSyncConsole": "लाइव डेटा सिंक कंसोल",
    "verifyPassiveIngestion": "एटलस मोंगोडीबी पर लाइव पैसिव इंजेक्शन और ऑफलाइन सिंक सत्यापित करें",
    "ingestSmsAlerts": "1. निष्क्रिय एसएमएस लेनदेन अलर्ट सिंक करें",
    "ingestSmsHelp": "पैसिव एग्रीगेटर सिमुलेशन के लिए एसएमएस टाइप या क्लिक करें। मेट्रिक्स को लाइव पुनर्गणना होते देखें।",
    "pasteSmsPlaceholder": "बैंक से प्राप्त एसएमएस संदेश यहां चिपकाएं...",
    "ingestSmsBtn": "एसएमएस दर्ज करें",
    "offlineQueueLedger": "2. ऑफलाइन सिंक और कतार बहीखाता",
    "queuedRecords": "कतारबद्ध रिकॉर्ड:",
    "noQueuedOps": "कोई कतारबद्ध कार्य नहीं। सिस्टम सिंक हुआ।",
    "forceOfflineSync": "ऑफलाइन सिंक जबरन मिलान करें",
    "activeAdvisories": "16 लेनदेन सिंक • 2 सक्रिय सलाह ध्यान योग्य।",
    "dialInCompanion": "आवाज अलर्ट कॉल (हिंदी / स्थानीय बोली)",
    "todaysAiAdvisories": "आज के एआई सलाह बुलेटिन",
    "dynamicallyUpdated": "गतिशील रूप से अपडेटेड",
    "simulatedCashPredictions": "सिम्युलेटेड नकद प्रवाह पूर्वानुमान (90 दिन)",
    "engineView": "इंजन दृश्य →",
    "whatsDriving": "इस पूर्वानुमान के मुख्य 3 कारण:",
    "openPassbook": "पासबुक खोलें →",
    "expandIndex": "अनुक्रमणिका विस्तार →",
    "dateCol": "दिनांक",
    "descCol": "विवरण",
    "catCol": "श्रेणी",
    "amtCol": "राशि",
    "cropCol": "फसल / उत्पाद",
    "rateCol": "दर",
    "adviceCol": "सलाह",
    "hold": "रोकें (HOLD)",
    "sell": "बेचें (SELL)",
    "buyNow": "अभी खरीदें",
    "buyLater": "बाद में खरीदें",
    "rbiSyncTitle": "आरबीआई अकाउंट एग्रीगेटर अनुमति सिंक",
    "smsConsentDesc": "डेबिट/क्रेडिट एसएमएस अलर्ट एक्सट्रेक्ट करें",
    "upiConsentDesc": "व्यापारी भुगतान सत्यापन एपीआई",
    "imdConsentDesc": "पशु गर्मी और दूध उपज गिरावट संबंध",
    "viewFull": "पूरा देखें →",
    "viewFullDebt": "पूरी एआई ऋण रणनीति देखें",
    "welcome": "नमस्ते रमेश! मैं ग्रामबॉट एआई हूं, आपका वित्तीय सहायक। मैं आपके गांव, आपकी डेयरी, अमूल और मौसम को समझता हूं। आज आपकी मदद कैसे करूं?",
    "voiceText": "सुन रहा हूँ...",
    "suggest1": "क्या मैं 26 जुलाई को ट्रैक्टर की ईएमआई भर पाऊंगा?",
    "suggest2": "आज मेरी वित्तीय स्थिति पीली (Yellow) क्यों है?",
    "suggest3": "सोमवार की गर्मी से मेरे दूध की बिक्री पर क्या असर होगा?",
    "suggest4": "यदि चारे की कीमत 10% बढ़ जाए तो क्या होगा?",
    "reply1": "हाँ, आप 26 जुलाई को ₹7,500 की ईएमआई आसानी से दे सकते हैं। अमूल से 22 जुलाई को आने वाले ₹8,200 के भुगतान के बाद आपके पास कुल ₹14,400 होंगे। आप बिल्कुल सुरक्षित हैं।",
    "reply2": "आपकी स्थिति पीली इसलिए है क्योंकि इस महीने चारे की कीमत 15% बढ़ गई है और सोमवार को गर्मी (37°C) के कारण दूध उत्पादन 12% कम होने की आशंका है। रोज ₹400 की बचत करें।",
    "reply3": "सोमवार को 37°C तापमान से गाय-भैंसों को गर्मी लगेगी। इससे रोजाना दूध उत्पादन 1.5 से 2 लीटर तक गिर सकता है जिससे ₹280 का नुकसान हो सकता है। पशुओं को ठंडा पानी और नमक दें।",
    "reply4": "यदि चारे की कीमत 10% बढ़ती है, तो आपका दैनिक खर्च ₹80 बढ़ जाएगा। आपकी नकदी का बैकअप 45 दिनों से घटकर 38 दिन रह जाएगा। संतुलन के लिए स्थानीय दुकान से ₹1,500 बकाया वसूलें।",
    "feedback": "क्या आपको यह सलाह समझ आई? (हाँ बोलें या अंगूठा दबाएं)",
    "offlineMsg": "ऑफ़लाइन मोड चालू है। आपकी सहायता बिना इंटरनेट के सीधे फोन के लोकल मॉडल द्वारा की जा रही है।",
    "fallback": "मैं समझ गया। कृपया चारे की मात्रा पर ध्यान दें और अपने नजदीकी अमूल सहकारी केंद्र के भाव चेक करें। ग्रामपल्स एआई की सलाह: इस हफ्ते अतिरिक्त कर्ज लेने से बचें।",
    "overviewPanel": "मुख्य डैशबोर्ड",
    "passbook": "पासबुक",
    "userProfile": "उपयोगकर्ता प्रोफ़ाइल",
    "debtStrategy": "ऋण रणनीति",
    "governmentSchemes": "सरकारी योजनाएं",
    "riskAnalysis": "जोखिम विश्लेषण",
    "syncStatus": "सिंक स्थिति",
    "liveSyncApi": "✓ लाइव एपीआई सिंक",
    "logOutAccount": "साइन आउट",
    "dataAsOf": "डेटा:",
    "masterSynced": "मास्टर सिंक",
    "sinceLastChecked": "पिछली जांच के बाद",
    "quickActions": "त्वरित कार्य:",
    "logTransaction": "लेनदेन दर्ज करें",
    "viewFullForecast": "पूर्ण पूर्वानुमान देखें",
    "registerLoanEmi": "ऋण / ईएमआई दर्ज करें",
    "voiceCompanion": "आवाज सहायक",
    "financialHealthIndex": "वित्तीय स्वास्थ्य सूचकांक",
    "predictedCashRunway": "अनुमानित नकद रनवे",
    "outstandingLoansEmi": "बकाया ऋण ईएमआई",
    "climateThermalStress": "जलवायु तापमान तनाव",
    "criticalRisk": "गंभीर खतरा",
    "warningAlert": "चेतावनी",
    "fullySafe": "पूरी तरह सुरक्षित",
    "safe": "सुरक्षित",
    "danger": "खतरा",
    "warning": "सावधान",
    "daysLeft": "दिन",
    "recentAlertsTitle": "हाल की चेतावनियां",
    "debtStrategyTitle": "एआई ऋण रणनीति सलाह",
    "riskAnalysisTitle": "व्यवसाय जोखिम विश्लेषण",
    "interactivePredictions": "पूर्वानुमान",
    "mandiPrices": "मंडी भाव",
    "weatherIntel": "मौसम",
    "rbiConsent": "आरबीआई सहमति",
    "enterpriseDashboard": "मुख्य व्यवसाय डैशबोर्ड",
    "scenarioForecastTitle": "नकद प्रवाह पूर्वानुमान",
    "mandiIntelTitle": "मंडी बाजार जानकारी",
    "passbookTitle": "लेनदेन पासबुक",
    "weatherPortalTitle": "मौसम पोर्टल",
    "schemesTitle": "सरकारी योजनाएं",
    "profileMgmtTitle": "व्यवसाय प्रोफ़ाइल प्रबंधन",
    "rbiConsentTitle": "आरबीआई सहमति सेटिंग्स",
    "totalMonthlyEmi": "कुल मासिक ईएमआई",
    "acrossActiveLoans": "सक्रिय ऋणों पर",
    "dtiRatio": "ऋण-से-आय (DTI)",
    "safeDtiZone": "✓ सुरक्षित DTI क्षेत्र",
    "debtStrategyDesc": "एआई आधारित नकद-प्रवाह और पुनर्भुगतान योजना।",
    "refreshAnalysis": "विश्लेषण रीफ्रेश करें",
    "registerNewLoan": "🏦 नया ऋण / ईएमआई दर्ज करें",
    "lenderBankName": "ऋणदाता बैंक का नाम",
    "bankPlaceholder": "जैसे एसबीआई कृषि शाखा",
    "monthlyEmiAmount": "मासिक ईएमआई राशि",
    "registerDebtBtn": "ऋण दर्ज करें",
    "welcomeBack": "नमस्ते",
    "searchTransactions": "लेनदेन खोजें...",
    "exportBankCsv": "बैंक CSV डाउनलोड करें",
    "registerBusiness": "नया सूक्ष्म उद्यम दर्ज करें",
    "logManualTxn": "मैन्युअल लेनदेन दर्ज करें",
    "rbiConsentDashboard": "आरबीआई AA सहमति डैशबोर्ड",
    "revokeAllAccess": "सभी एक्सेस रद्द करें",
    "auditTrailTitle": "ऑडिट ट्रेल",
  },
  mr: {
    "debtStrategyDesc": "एआय आधारित रोख-प्रवाह जुळणी आणि परतफेड नियोजन मार्गदर्शक तत्त्वे.",
    "refinancingChecklist": "पुनर्वित्त दस्तऐवज चेकलिस्ट",
    "refreshAnalysis": "विश्लेषण रीफ्रेश करा",
    "analyzingObligations": "कर्ज दायित्वे आणि रोख प्रवाहाचे विश्लेषण करत आहे...",
    "totalMonthlyEmi": "एकूण मासिक ईएमआय",
    "acrossActiveLoans": "सक्रिय कर्जांवर",
    "dtiRatio": "कर्ज-ते-उत्पन्न (DTI)",
    "safeDtiZone": "✓ सुरक्षित DTI क्षेत्र",
    "moderateBurden": "⚠ मध्यम भार",
    "highRiskDti": "🔴 उच्च धोक्याचे DTI",
    "totalOutstandingDebt": "एकूण थकीत कर्ज",
    "principalRemaining": "मुद्दल शिल्लक",
    "priorityQueueTitle": "एआय शिफारस केलेली परतफेडीची प्राधान्य क्रमवारी",
    "rankedByRisk": "धोका आणि दंड दरानुसार क्रमवारी",
    "highPriorityCovered": "उच्च प्राधान्य (सुरक्षित)",
    "urgentShortfall": "तातडीचे (तुटवडा)",
    "activeStrategiesTitle": "सक्रिय कर्ज रणनीती आणि हप्ता वेळापत्रक",
    "onTimeTrackRecord": "✓ १२/१२ वेळेवर",
    "amortizationBtn": "कर्ज हप्ता वेळापत्रक 📊",
    "emiMonth": "ईएमआय / महिना",
    "cashAvailable": "उपलब्ध रोख",
    "expectedIncoming": "अपेक्षित येणे",
    "shortfall": "तुटवडा (Shortfall)",
    "surplus": "शिल्लक (Surplus)",
    "outstanding": "थकीत",
    "aiStrategy": "एआय रणनीती",
    "registerNewLoan": "🏦 नवीन कर्ज / ईएमआय नोंदवा",
    "submitEmiSub": "रोख सुरक्षा पाहण्यासाठी सक्रिय ईएमआय नोंदवा.",
    "lenderBankName": "कर्ज देणाऱ्या बँकेचे नाव",
    "bankPlaceholder": "उदा. एसबीआय कृषी शाखा",
    "loanTypeCategory": "कर्ज प्रकार श्रेणी",
    "monthlyEmiAmount": "मासिक ईएमआय रक्कम",
    "totalOutstandingLabel": "एकूण थकीत रक्कम",
    "daysToDueDate": "देय तारखेपर्यंत दिवस",
    "registerDebtBtn": "कर्ज नोंदणी करा",
    "repaymentGuidelines": "परतफेड मार्गदर्शक तत्त्वे",
    "guidelineParagraph1": "थकीत ईएमआयची नोंदणी केल्याने एआय इंजिन तुमचा रोख कालावधी सुरक्षित असल्याची खात्री करते.",
    "guidelineParagraph2": "तुटवडा असल्यास लाल रंगाचा इशारा दिसेल. उपाययोजनांसाठी शिफारसी तपासा.",
    "monitoringUnit": "सक्रिय युनिट:",
    "villageCluster": "गाव क्लस्टर:",
    "districtJurisdiction": "जिल्हा क्षेत्र:",
    "primaryIndustry": "प्राथमिक उद्योग:",
    "aaConsentApi": "एए संमती एपीआय:",
    "creditConfidenceScore": "क्रेडिट विश्वास स्कोर:",
    "liveSyncConsole": "लाईव्ह डेटा सिंक कन्सोल",
    "verifyPassiveIngestion": "ॲटलास मोंगोडीबी वर लाईव्ह पॅसिव्ह डेटा आणि ऑफलाईन सिंक तपासा",
    "ingestSmsAlerts": "१. पॅसिव्ह एसएमएस व्यवहार अलर्ट सिंक करा",
    "ingestSmsHelp": "पॅसिव्ह डेटा सिम्युलेटरसाठी एसएमएस निवडा किंवा टाईप करा. मेट्रिक्स अपडेट पहा.",
    "pasteSmsPlaceholder": "बँकेचा एसएमएस येथे पेस्ट करा...",
    "ingestSmsBtn": "एसएमएस नोंदवा",
    "offlineQueueLedger": "२. ऑफलाईन सिंक आणि रांग बहीखाता",
    "queuedRecords": "रांगेतील नोंदी:",
    "noQueuedOps": "रांगेत कोणतीही कृती नाही. प्रणाली सिंक झाली.",
    "forceOfflineSync": "ऑफलाईन सिंक तात्काळ जुळवून घ्या",
    "activeAdvisories": "१६ व्यवहार सिंक • २ सक्रिय इशारे लक्ष देण्यायोग्य.",
    "dialInCompanion": "आवाज अलर्ट कॉल (मराठी / बोलीभाषा)",
    "todaysAiAdvisories": "आजचे एआय सल्लागार बुलेटिन",
    "dynamicallyUpdated": "डायनामिक अपडेट केलेले",
    "simulatedCashPredictions": "अंदाजित रोख प्रवाह अंदाज (९० दिवस)",
    "engineView": "इंजिन दृश्य →",
    "whatsDriving": "या अंदाजाचे मुख्य ३ घटक:",
    "openPassbook": "पासबुक उघडा →",
    "expandIndex": "निर्देशांक पहा →",
    "dateCol": "तारीख",
    "descCol": "तपशील",
    "catCol": "वर्ग",
    "amtCol": "रक्कम",
    "cropCol": "पीक / वस्तू",
    "rateCol": "दर",
    "adviceCol": "सल्ला",
    "hold": "थांबा (HOLD)",
    "sell": "विक्री करा (SELL)",
    "buyNow": "आत्ताच खरेदी करा",
    "buyLater": "नंतर खरेदी करा",
    "rbiSyncTitle": "आरबीआय अकाउंट ॲग्रिगेटर संमती सिंक",
    "smsConsentDesc": "डेबिट/क्रेडिट एसएमएस अलर्ट शोधा",
    "upiConsentDesc": "व्यापारी पेमेंट पडताळणी एपीआय",
    "imdConsentDesc": "हवामान ताण आणि दूध उत्पादन घट संबंध",
    "viewFull": "पूर्ण पहा →",
    "viewFullDebt": "संपूर्ण एआय कर्ज रणनीती पहा",
    "welcome": "नमस्कार रमेश! मी ग्रामबॉट एआय आहे, आपला शेती व आर्थिक सल्लागार. मी आपले गाव, डेअरी आणि हवामान समजून घेतो. आज मी काय मदत करू?",
    "voiceText": "ऐकत आहे...",
    "suggest1": "मी २६ जुलै रोजी ट्रॅक्टरची ईएमआय भरू शकेन का?",
    "suggest2": "आज माझी आर्थिक स्थिती पिवळी (Yellow) का आहे?",
    "suggest3": "सोमवारच्या उष्णतेचा माझ्या दूध विक्रीवर काय परिणाम होईल?",
    "suggest4": "चारा खर्च १०% वाढला तर काय होईल?",
    "reply1": "होय, तुम्ही २६ जुलैची ₹७,५०० ची ईएमआय सहज भरू शकता. २२ जुलै रोजी अमूलकडून ₹८,२०० चे पेमेंट येणार आहे, ज्यामुळे तुमच्या खात्यात ₹१४,४०० शिल्लक असतील. तुम्ही सुरक्षित आहात.",
    "reply2": "चारा खर्च १५% वाढल्यामुळे आणि सोमवारी तापमान ३७°C पर्यंत जाणार असल्यामुळे दूध उत्पादन १२% घटण्याची शक्यता आहे. म्हणूनच तुमची स्थिती पिवळी दाखवत आहे. रोज ₹४०० वाचवा.",
    "reply3": "सोमवारी ३७°C तापमानामुळे जनावरांना त्रास होईल. यामुळे दिवसाला दीड ते दोन लिटर दूध कमी निघेल आणि ₹२८० चे नुकसान होऊ शकते. जनावरांना थंड पाणी आणि गुळ द्या.",
    "reply4": "चारा १०% महागल्यास रोजचा खर्च ₹८० वाढेल आणि आर्थिक बॅकअप ४५ दिवसांवरून ३८ दिवसांवर येईल. गावातील दुकानांमधून जुने ₹१,५०० वसूल करा.",
    "feedback": "तुम्हाला सल्ला समजला का? (होय बोला किंवा अंगठा दाबा)",
    "offlineMsg": "ऑफलाईन काम करत आहे. इंटरनेटशिवाय थेट तुमच्या फोनवरील लोकल मॉडेलद्वारे सल्ला दिला जात आहे.",
    "fallback": "मी समजलो. कृपया चाऱ्याच्या प्रमाणावर लक्ष ठेवा आणि तुमच्या जवळच्या सहकारी दूध केंद्राचे दर तपासा। ग्रामपल्स एआयचा सल्ला: या आठवड्यात नवीन कर्ज घेणे टाळा।",
    "backToHome": "मुख्यपृष्ठावर मागे जा",
    "todayFinancialHealth": "आजचे आर्थिक आरोग्य",
    "criticalRisk": "गंभीर धोका",
    "warningAlert": "इशारा अलर्ट",
    "fullySafe": "पूर्ण सुरक्षित",
    "healthIndex": "आरोग्य निर्देशांक",
    "days30": "३० दिवस",
    "days60": "६० दिवस",
    "days90": "९० दिवस",
    "safe": "✓ सुरक्षित",
    "warning": "⚠ इशारा",
    "danger": "⚠ धोका",
    "secure": "✓ सुरक्षित",
    "stressed": "ताणतणाव",
    "todayAISummary": "आजचा एआय सारांश",
    "checkForecast": "अंदाज तपासा",
    "emiStatus": "ईएमआय स्थिती",
    "weatherIntel": "हवामान माहिती",
    "mandiPrices": "बाजार भाव",
    "whatsappInfo": "व्हॉट्सॲप माहिती",
    "speakAlert": "आवाज अलर्ट",
    "weatherTitle": "आयएमडी स्थानिक हवामान माहिती",
    "impactTitle": "पशू आणि पिकांवर एआय व्यवसाय प्रभाव",
    "forecast7DaysTitle": "७-दिवसीय स्थानिक अंदाज",
    "mandiTitle": "एगमार्कनेट बाजार भाव आणि एआय सल्ला",
    "mandiUnit": "एकक (Unit)",
    "mandiTrend": "कल (Trend)",
    "mandiUp": "▲ वाढता",
    "mandiDown": "▼ घटता",
    "mandiStable": "● स्थिर",
    "nearbyMarketsTitle": "जवळचे बाजार",
    "upcomingEMITitle": "आगामी बँक ईएमआय पेमेंट्स",
    "emiAmountTitle": "ईएमआय रक्कम",
    "liquidCashTitle": "शिल्लक रोख रक्कम",
    "safetyStrategyTitle": "एआय ईएमआय सुरक्षा रणनीती",
    "daysLeft": "दिवस शिल्लक",
    "consentedLedgerTitle": "डिजिटल बहीखाते (SMS/UPI)",
    "ledgerSub": "मॅन्युअल एन्ट्रीची गरज नाही. एसएमएस आणि यूपीआय द्वारे स्वयंचलित.",
    "recentAlertsTitle": "नुकतेच एआय व्हॉट्सॲप-स्टाईल अलर्ट",
    "criticalAlertBadge": "महत्त्वाचा इशारा",
    "warningAlertBadge": "चेतावणी इशारा",
    "advisoryBadge": "सल्लागार",
    "whatsappMockBanner": "व्हॉट्सॲप संदेश:",
    "commonQuestions": "सामान्य प्रश्न (सुझाव)",
    "askGramPulse": "ग्रामपल्सला काहीही विचारा...",
    "listenVoice": "आवाज ऐका",
    "villageDistrict": "गाव/जिल्हा",
    "businessCategory": "व्यवसाय श्रेणी",
    "loanLinked": "लिंक केलेले कर्ज",
    "rbiConsent": "आरबीआय डेटा परवानग्या",
    "smsReader": "एसएमएस व्यवहार रीडर (स्वयंचलित पासबुक)",
    "upiLinking": "यूपीआय पेमेंट्स लिंकिंग",
    "imdWeather": "आयएमडी हवामान परस्परसंबंध",
    "resetOnboarding": "ऑनबोर्डिंग रीसेट करा",
    "logOut": "खाते लॉग आउट करा",
    "profileConsentDashboard": "प्रोफाइल आणि एआय संमती डॅशबोर्ड",
    "aiCashFlowForecast": "एआय रोख प्रवाह अंदाज",
    "interactivePredictions": "अंदाज आणि परिस्थिती",
    "criticalDangerZone": "गंभीर धोका क्षेत्र (₹५,०००)",
    "cashRemaining": "रोख शिल्लक",
    "predictedIncome": "अंदाजित उत्पन्न",
    "expenses": "खर्च",
    "predictionResult": "अंदाज निकाल",
    "scenarioSimulatorTitle": "एआय सिनॅरिओ सिम्युलेटर ('काय होईल जर?' नियोजक)",
    "interactiveExplanation": "रोख प्रवाहाचा अंदाज तात्काळ पाहण्यासाठी खालील मूल्ये बदला!",
    "whatIfMilkRate": "जर दूध फॅटचा दर कमी झाला तर?",
    "whatIfSalesVolume": "बिक्रीचे प्रमाण कमी झाले तर?",
    "whatIfFeedCost": "चारा खर्च महाग झाला तर?",
    "heavyRainfallDisruption": "मुसळधार पाऊस व्यत्यय?",
    "heavyRainfallSub": "दूध टँकर आणि पुरवठा मार्गांना ३+ तास उशीर होईल",
    "aiConfidenceScore": "एआय आत्मविश्वास स्कोर",
    "howItWorks": "हे कसे कार्य करते",
    "redAdvice": "धोका: अनेक घटकांमुळे तुमचा रोख शिल्लक कमी झाला आहे. नवीन खरेदी टाळा, गावातील थकीत रक्कम वसूल करा आणि सूक्ष्म पत योजनेचा लाभ घ्या.",
    "yellowAdvice": "सावधानता: चारा खर्च वाढल्यामुळे तुमची रोख शिल्लक धोका रेषेजवळ येत आहे. मोठा खर्च टाळा आणि हवामानावर लक्ष ठेवा.",
    "greenAdvice": "उत्कृष्ट: तुमचे रोख नियोजन अतिशय सुरक्षित आहे. तुमच्याकडे सर्व ईएमआय भरण्यासाठी आणि व्यवसाय वाढवण्यासाठी पुरेसा निधी आहे.",
    "overviewPanel": "मुख्य डॅशबोर्ड",
    "passbook": "पासबुक",
    "userProfile": "वापरकर्ता प्रोफाइल",
    "debtStrategy": "कर्ज रणनीती",
    "governmentSchemes": "शासकीय योजना",
    "riskAnalysis": "धोका विश्लेषण",
    "welcomeBack": "नमस्कार",
    "enterpriseDashboard": "मुख्य व्यवसाय डॅशबोर्ड",
    "scenarioForecastTitle": "रोख प्रवाह अंदाज आणि परिस्थिती",
    "mandiIntelTitle": "बाजार भाव बुद्धिमत्ता",
    "passbookTitle": "व्यवहार पासबुक",
    "weatherPortalTitle": "हवामान बुद्धिमत्ता पोर्टल",
    "schemesTitle": "शासकीय योजना आणि एआय शिफारसी",
    "profileMgmtTitle": "व्यवसाय प्रोफाइल व्यवस्थापन",
    "rbiConsentTitle": "आरबीआय संमती आणि गोपनीयता सेटिंग्ज",
    "debtStrategyTitle": "एआय कर्ज रणनीती सल्ला",
    "riskAnalysisTitle": "व्यवसाय धोका विश्लेषण",
    "financialHealthIndex": "आर्थिक आरोग्य निर्देशांक",
    "predictedCashRunway": "अंदाजित रोख कालावधी (Runway)",
    "outstandingLoansEmi": "थकीत कर्ज ईएमआय",
    "climateThermalStress": "हवामान व तापमान ताण",
    "sinceLastChecked": "शेवटच्या तपासणीनंतरचा सारांश",
    "quickActions": "जलद कृती:",
    "logTransaction": "व्यवहार नोंदवा",
    "viewFullForecast": "पूर्ण अंदाज पहा",
    "registerLoanEmi": "कर्ज / ईएमआय नोंदवा",
    "voiceCompanion": "आवाज सहाय्यक",
    "dataAsOf": "माहिती वेळ:",
    "masterSynced": "मास्टर सिंक झाले",
    "syncStatus": "सिंक स्थिती",
    "liveSyncApi": "✓ लाईव्ह सिंक एपीआय",
    "logOutAccount": "खाते लॉग आउट करा",
    "bestTimeToSellTitle": "एआय 'विक्रीची सर्वोत्तम वेळ' शिफारस",
    "setPriceAlert": "किंमत अलर्ट मर्यादा ठरवा",
    "netPriceComparison": "वाहतूक खर्च समायोजित निव्वळ किंमत तुलना (जवळचे बाजार)",
    "apmcMarket": "एपीएमसी बाजार",
    "distance": "अंतर",
    "grossPrice": "एकूण किंमत",
    "estTransport": "अंदाजित वाहतूक खर्च",
    "netPriceRealized": "मिळालेली निव्वळ किंमत",
    "trackCustomMandi": "कस्टम बाजार पीक नोंदवा",
    "historicalComparison": "ऐतिहासिक हवामान तुलना",
    "prepChecklist": "हवामान पूर्वतयारी चेकलिस्ट",
    "reportDisruption": "हवामान व्यत्यय अहवाल द्या",
    "exportBankCsv": "बँक CSV डाउनलोड करा",
    "searchTransactions": "व्यवहार शोधा...",
    "allCategories": "सर्व श्रेणी",
    "incomeOnly": "फक्त उत्पन्न",
    "expenseOnly": "फक्त खर्च",
    "duplicateDetectorActive": "✓ डुप्लिकेट शोध कार्यन्वित",
    "logManualTxn": "मॅन्युअल व्यवहार नोंदवा",
    "rbiConsentDashboard": "आरबीआय अकाउंट ॲग्रिगेटर (AA) संमती डॅशबोर्ड",
    "revokeAllAccess": "सर्व प्रवेश रद्द करा",
    "dataAuditLog": "क्रिप्टोग्राफिक डेटा प्रवेश ऑडिट नोंद (शेवटचे ५ प्रयत्न)",
    "creditConfidence": "क्रेडिट विश्वास स्कोर",
    "auditTrailTitle": "फील्ड पडताळणी ऑडिट ट्रेल",
  },
  gu: {
    "monitoringUnit": "સક્રિય એકમ:",
    "villageCluster": "ગામ ક્લસ્ટર:",
    "districtJurisdiction": "જિલ્લા ક્ષેત્ર:",
    "primaryIndustry": "મુખ્ય ઉદ્યોગ:",
    "aaConsentApi": "AA સંમતિ API:",
    "creditConfidenceScore": "ક્રેડિટ વિશ્વાસ સ્કોર:",
    "liveSyncConsole": "લાઇવ ડેટા સિંક કન્સોલ",
    "verifyPassiveIngestion": "એટલાસ મોંગોડીબી પર લાઇવ ડેટા સિંક ચકાસો",
    "ingestSmsAlerts": "૧. નિષ્ક્રિય SMS વ્યવહાર એલર્ટ ઉમેરો",
    "ingestSmsHelp": "ડેટા સિંક માટે SMS ટાઇપ અથવા સિલેક્ટ કરો.",
    "pasteSmsPlaceholder": "બેંકનો SMS અહીં પેસ્ટ કરો...",
    "ingestSmsBtn": "SMS ઉમેરો",
    "offlineQueueLedger": "૨. ઓફલાઇન સિંક ખાતાવહી",
    "queuedRecords": "લાઇનમાં રહેલ રેકોર્ડ:",
    "noQueuedOps": "કોઈ લાઇન રેકોર્ડ નથી. સિસ્ટમ સિંક થઈ.",
    "forceOfflineSync": "ઓફલાઇન સિંક પુનઃપ્રાપ્ત કરો",
    "activeAdvisories": "૧૬ વ્યવહારો સિંક • ૨ સક્રિય સલાહ.",
    "dialInCompanion": "અવાજ કોલ એલર્ટ",
    "todaysAiAdvisories": "આજના AI સલાહ બુલેટિન",
    "dynamicallyUpdated": "ડાયનેમિક અપડેટ થયેલ",
    "simulatedCashPredictions": "અંદાજિત કેશ ફ્લો પૂર્વાનુમાન (૯૦ દિવસ)",
    "engineView": "એન્જિન દ્રશ્ય →",
    "whatsDriving": "આ અંદાજના મુખ્ય ૩ પરિબળો:",
    "openPassbook": "પાસબુક ખોલો →",
    "expandIndex": "અનુક્રમણિકા વિસ્તારો →",
    "dateCol": "તારીખ",
    "descCol": "વિગત",
    "catCol": "શ્રેણી",
    "amtCol": "રકમ",
    "cropCol": "પાક / વસ્તુ",
    "rateCol": "ભાવ",
    "adviceCol": "સલાહ",
    "hold": "સાચવો (HOLD)",
    "sell": "વેચો (SELL)",
    "buyNow": "હવે ખરીદો",
    "buyLater": "પછી ખરીદો",
    "rbiSyncTitle": "RBI સંમતિ ડેટા સિંક",
    "smsConsentDesc": "SMS એલર્ટસ એક્સટ્રેક્ટ કરો",
    "upiConsentDesc": "પેમેન્ટ ચકાસણી API",
    "imdConsentDesc": "હવામાન અસર ગણતરી",
    "viewFull": "સંપૂર્ણ જુઓ →",
    "viewFullDebt": "સંપૂર્ણ AI દેવું વ્યૂહરચના જુઓ",
    "welcome": "નમસ્તે રમેશભાઈ! હું ગ્રામબોટ AI છું, તમારા આર્થિક સલાહકાર. હું તમારું ગામ, તમારી ડેરી, અમૂલ અને હવામાન સમજું છું. આજે હું તમારી શું મદદ કરું?",
    "voiceText": "સાંભળી રહ્યું છે...",
    "suggest1": "શું હું ૨૬ જુલાઈએ ટ્રેક્ટરની EMI ભરી શકીશ?",
    "suggest2": "આજે મારી આર્થિક સ્થિતિ પીળી (Yellow) કેમ છે?",
    "suggest3": "સોમવારની ગરમીથી દૂધના વેચાણ પર શું અસર થશે?",
    "suggest4": "જો પશુ આહારનો ખર્ચ ૧૦% વધી જાય તો શું થાય?",
    "reply1": "હા, તમે ૨૬ જુલાઈએ ₹૭,૫૦૦ ની EMI સરળતાથી ચૂકવી શકો છો. ૨૨ જુલાઈએ અમૂલ તરફથી ₹૮,૨૦૦ આવવાના છે, જેથી તમારી પાસે ₹૧૪,૪૦૦ ની બચત થશે. તમે સુરક્ષિત છો.",
    "reply2": "આ મહિને પશુ આહાર ૧૫% મોંઘો થયો છે અને સોમવારે ગરમી (૩૭°C) ના કારણે દૂધનું ઉત્પાદન ૧૨% ઘટવાની ધારણા હોવાથી તમારી સ્થિતિ પીળી છે. રોજ ₹૪૦૦ બચાવો.",
    "reply3": "સોમવારે ૩૭°C તાપમાનના લીધે પશુઓ દૂધ ઓછું આપશે. રોજ ૧.૫ થી ૨ લીટરનો ઘટાડો થતાં ₹૨८૦ નું નુકસાન થઈ શકે છે. પશુઓને ઠંડુ પાણી અને ગોળનું પાણી આપો.",
    "reply4": "જો પશુ આહાર ૧૦% મોંઘો થાય તો રોજનો ખર્ચ ₹૮૦ વધશે. તમારી નાણાકીય ક્ષમતા ૪૫ દિવસથી ઘટીને ૩૮ દિવસ થશે. દુકાનદાર પાસેથી લેણાં ₹૧,૫૦૦ તરત ઉઘરાવો.",
    "feedback": "શું તમને આ સલાહ સમજાઈ ગઈ? (હા બોલો અથવા અંગૂઠો દબાવો)",
    "offlineMsg": "ઓફલાઇન મોડ ચાલુ છે. ઇન્ટરનેટ વિના સીધા ફોનના લોકલ મોડેલ દ્વારા ગણતરી કરવામાં આવી રહી છે.",
    "fallback": "હું સમજી ગયો. દૂધના ભાવ થોડા દિવસોમાં સુધરશે. પશુ આહારમાં અનાજનું પ્રમાણ સરખું રાખો. ગ્રામપલ્સ AI સલાહ: આ સપ્તાહે વધારાનું દેવું ટાળો.",
    "overviewPanel": "મુખ્ય ડૅશબોર્ડ",
    "passbook": "પાસબૂક",
    "userProfile": "પ્રોફ઀ઇલ",
    "debtStrategy": "દેવું વ્યૂહ",
    "governmentSchemes": "સરકારી યોજના",
    "riskAnalysis": "જોખમ વિશ્લેષણ",
    "syncStatus": "સિંક સ્થિતિ",
    "liveSyncApi": "✓ લાઇવ API સિંક",
    "logOutAccount": "સાઇન આઉટ",
    "dataAsOf": "ડેટા:",
    "masterSynced": "માસ્ટર સિંક",
    "sinceLastChecked": "છેલ્લી તપાસ પછી",
    "quickActions": "ઝડપી ક્રિયાઓ:",
    "logTransaction": "વ્યવહાર નોંધો",
    "viewFullForecast": "સંપૂર્ણ અંદાજ",
    "registerLoanEmi": "ઋણ / EMI નોંધો",
    "voiceCompanion": "અવાજ સહાયક",
    "financialHealthIndex": "નાણાકીય આરોગ્ય સૂચકાંક",
    "predictedCashRunway": "અંદાજિત રોકડ અવધિ",
    "outstandingLoansEmi": "બાકી ઋણ EMI",
    "climateThermalStress": "આબોહવા તાપ તણાવ",
    "criticalRisk": "ગંભીર જોખમ",
    "warningAlert": "ચેતવણી",
    "fullySafe": "સંપૂર્ણ સુરક્ષિત",
    "safe": "સુરક્ષિત",
    "danger": "જોખમ",
    "warning": "સાવધ",
    "daysLeft": "દિવસ",
    "recentAlertsTitle": "તાજેતરી ચેતવણીઓ",
    "interactivePredictions": "અંદાજ",
    "mandiPrices": "મંડી ભાવ",
    "weatherIntel": "હવામાન",
    "rbiConsent": "RBI સહમતિ",
    "enterpriseDashboard": "મુખ્ય ડૅશબોર્ડ",
    "debtStrategyTitle": "AI ઋણ વ્યૂહ",
    "riskAnalysisTitle": "જોખમ વિશ્લેષણ",
    "totalMonthlyEmi": "કુલ માસિક EMI",
    "refreshAnalysis": "વિશ્લેષણ રિફ્રેશ",
    "registerNewLoan": "🏦 નવું ઋણ / EMI નોંધો",
    "registerDebtBtn": "ઋણ નોંધો",
    "welcomeBack": "આવો",
    "searchTransactions": "વ્યવહાર શોધો...",
    "debtStrategyDesc": "AI આધારિત રોકડ-પ્રવાહ અને ચૂકવણી આયોજન.",
    "logManualTxn": "મૈન્યુઅલ વ્યવહાર",
    "registerBusiness": "નવો ઉદ્યોગ નોંધો",
    "rbiConsentDashboard": "RBI AA સહમતિ ડૅશબોર્ડ",
    "revokeAllAccess": "બધી ઍક્સેસ રદ",
    "exportBankCsv": "બૅન્ક CSV ડાઉનલોડ",
  },
  pa: {
    "welcome": "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਰਮੇਸ਼! ਮੈਂ ਗ੍ਰਾਮਬੋਟ AI ਹਾਂ, ਤੁਹਾਡਾ ਵਿੱਤੀ ਸਹਾਇਕ। ਮੈਂ ਤੁਹਾਡਾ ਪਿੰਡ, ਤੁਹਾਡੀ ਡੇਅਰੀ, ਅਮੂਲ ਅਤੇ ਮੌਸਮ ਨੂੰ ਸਮਝਦਾ ਹਾਂ। ਅੱਜ ਤੁਹਾਡੀ ਮਦਦ ਕਿਵੇਂ ਕਰਾਂ?",
    "voiceText": "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
    "suggest1": "ਕੀ ਮੈਂ 26 ਜੁਲਾਈ ਨੂੰ ਟਰੈਕਟਰ ਦੀ EMI ਭਰ ਸਕਦਾ ਹਾਂ?",
    "suggest2": "ਅੱਜ ਮੇਰੀ ਵਿੱਤੀ ਸਥਿਤੀ ਪੀਲੀ (Yellow) ਕਿਉਂ ਹੈ?",
    "suggest3": "ਸੋਮਵਾਰ ਦੀ ਗਰਮੀ ਦਾ ਮੇਰੇ ਦੁੱਧ ਦੀ ਵਿਕਰੀ 'ਤੇ ਕੀ ਅਸਰ ਪਵੇਗਾ?",
    "suggest4": "ਜੇਕਰ ਚਾਰੇ ਦੀ ਕੀਮਤ 10% ਵੱਧ ਜਾਵੇ ਤਾਂ ਕੀ ਹੋਵੇਗਾ?",
    "reply1": "ਹਾਂ, ਤੁਸੀਂ 26 ਜੁਲਾਈ ਨੂੰ ₹7,500 ਦੀ EMI ਆਸਾਨੀ ਨਾਲ ਦੇ ਸਕਦੇ ਹੋ। ਅਮੂਲ ਤੋਂ 22 ਜੁਲਾਈ ਨੂੰ ਆਉਣ ਵਾਲੇ ₹8,200 ਦੇ ਭੁਗਤਾਨ ਤੋਂ ਬਾਅਦ ਤੁਹਾਡੇ ਕੋਲ ₹14,400 ਹੋਣਗੇ। ਤੁਸੀਂ ਬਿਲਕੁਲ ਸੁਰੱਖਿਅਤ ਹੋ।",
    "reply2": "ਤੁਹਾਡੀ ਸਥਿਤੀ ਪੀਲੀ ਇਸ ਲਈ ਹੈ ਕਿਉਂਕਿ ਇਸ ਮਹੀਨੇ ਚਾਰੇ ਦੀ ਕੀਮਤ 15% ਵਧ ਗਈ ਹੈ ਅਤੇ ਸੋਮਵਾਰ ਨੂੰ ਗਰਮੀ (37°C) ਕਾਰਨ ਦੁੱਧ ਦਾ ਉਤਪਾਦਨ 12% ਘੱਟ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ ਹੈ। ਰੋਜ਼ ₹400 ਦੀ ਬਚਤ ਕਰੋ।",
    "reply3": "ਸੋਮਵਾਰ ਨੂੰ 37°C ਤਾਪਮਾਨ ਨਾਲ ਪਸ਼ੂਆਂ ਨੂੰ ਗਰਮੀ ਲੱਗੇਗੀ। ਇਸ ਨਾਲ ਰੋਜ਼ਾਨਾ ਦੁੱਧ ਦਾ ਉਤਪਾਦਨ 1.5 ਤੋਂ 2 ਲੀਟਰ ਤੱਕ ਡਿੱਗ ਸਕਦਾ ਹੈ ਜਿਸ ਨਾਲ ₹280 ਦਾ ਨੁਕਸਾਨ ਹੋ ਸਕਦਾ ਹੈ। ਪਸ਼ੂਆਂ ਨੂੰ ਠੰਡਾ ਪਾਣੀ ਅਤੇ ਗੁੜ ਦਿਓ।",
    "reply4": "ਜੇਕਰ ਚਾਰੇ ਦੀ ਕੀਮਤ 10% ਵਧਦੀ ਹੈ, ਤਾਂ ਤੁਹਾਡა ਰੋਜ਼ਾਨਾ ਖਰਚਾ ₹80 ਵਧ ਜਾਵੇਗਾ। ਤੁਹਾਡੀ ਨਕਦੀ ਦਾ ਬੈਕਅੱਪ 45 ਦਿਨਾਂ ਤੋਂ ਘਟ ਕੇ 38 ਦਿਨ ਰਹਿ ਜਾਵੇਗਾ। ਸੰਤੁਲਨ ਲਈ ਸਥਾਨਕ ਦੁਕਾਨ ਤੋਂ ₹1,500 ਬਕਾਇਆ ਵਸੂਲੋ।",
    "feedback": "ਕੀ ਤੁਹਾਨੂੰ ਇਹ ਸਲਾਹ ਸਮਝ ਆਈ? (ਹਾਂ ਬੋਲੋ ਜਾਂ ਅੰਗੂਠਾ ਦਬਾਓ)",
    "offlineMsg": "ਔਫਲਾਈਨ ਮੋਡ ਚਾਲੂ ਹੈ। ਤੁਹਾਡੀ ਸਹਾਇਤਾ ਬਿਨਾਂ ਇੰਟਰਨੈਟ ਦੇ ਸਿੱਧੇ ਫੋਨ ਦੇ ਲੋਕਲ ਮਾਡਲ ਦੁਆਰਾ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ।",
    "fallback": "ਮੈਂ ਸਮਝ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਚਾਰੇ ਦੀ ਮਾਤਰਾ 'ਤੇ ਧਿਆਨ ਦਿਓ ਅਤੇ ਨਜ਼ਦੀਕੀ ਸਹਿਕਾਰੀ ਕੇਂਦਰ ਦੇ ਭਾਅ ਚੈੱਕ ਕਰੋ। ਗ੍ਰਾਮਪਲਸ ਏਆਈ ਦੀ ਸਲਾਹ: ਇਸ ਹਫ਼ਤੇ ਹੋਰ ਕਰਜ਼ਾ ਲੈਣ ਤੋਂ ਬਚੋ।",
  },
  ta: {
    "welcome": "வணக்கம் ரமேஷ்! நான் கிராம்பாட் AI, உங்கள் நிதி உதவியாளர். உங்கள் கிராமம், உங்கள் பால் பண்ணை, அமுல் மற்றும் வானிலை பற்றி எனக்குத் தெரியும். இன்று உங்களுக்கு நான் எவ்வாறு உதவட்டும்?",
    "voiceText": "கேட்டுக் கொண்டிருக்கிறது...",
    "suggest1": "ஜூலை 26-ல் எனது டிராக்டர் EMI-யை செலுத்த முடியுமா?",
    "suggest2": "இன்று எனது நிதி நிலை ஏன் மஞ்சள் (Yellow) நிறத்தில் உள்ளது?",
    "suggest3": "திங்கட்கிழமை வெயில் எனது பால் விற்பனையை எவ்வாறு பாதிக்கும்?",
    "suggest4": "தீவனச் செலவு 10% உயர்ந்தால் என்ன ஆகும்?",
    "reply1": "ஆம், ஜூலை 26 அன்று ₹7,500 EMI-யை நீங்கள் எளிதாக செலுத்தலாம். ஜூலை 22 அன்று அமுல் நிறுவனத்திடமிருந்து வரவிருக்கும் ₹8,200 கொடுப்பனவுக்குப் பிறகு உங்களிடம் ₹14,400 இருக்கும். நீங்கள் முழுமையாக பாதுகாப்பாக உள்ளீர்கள்.",
    "reply2": "இந்த மாத தீவனச் செலவு 15% அதிகரித்துள்ளதாலும், திங்கட்கிழமை வெயில் (37°C) காரணமாக பால் உற்பத்தி 12% குறைய வாய்ப்புள்ளதாலும் உங்கள் நிலை மஞ்சள் நிறத்தில் உள்ளது. தினமும் ₹400 சேமிக்கவும்.",
    "reply3": "திங்கட்கிழமை 37°C வெயிலால் மாடுகளுக்கு வெப்ப அழுத்தம் ஏற்படும். இதனால் தினசரி பால் உற்பத்தி 1.5 முதல் 2 லிட்டர் வரை குறைந்து ₹280 இழப்பு ஏற்படலாம். குளிர்ந்த நீர் மற்றும் வெல்லம் வழங்கவும்.",
    "reply4": "தீவன விலை 10% உயர்ந்தால், உங்கள் தினசரி செலவு ₹80 அதிகரிக்கும். உங்கள் பண இருப்பு 45 நாட்களிலிருந்து 38 நாட்களாகக் குறையும். சமநிலைப்படுத்த உள்ளூர் கடையிலிருந்து நிலுவைத் தொகை ₹1,500-ஐ வசூலிக்கவும்.",
    "feedback": "இந்த ஆலோசனை உங்களுக்குப் புரிந்ததா? (ஆம் என்று சொல்லவும் அல்லது தம்ஸ் அப் செய்யவும்)",
    "offlineMsg": "ஆஃப்லைனில் இயங்குகிறது. இணையம் இல்லாமல் உங்கள் தொலைபேசியின் உள்ளூர் மாடல் மூலம் ஆலோசனை வழங்கப்படுகிறது.",
    "fallback": "புரிந்து கொண்டேன். தீவனத்தின் அளவைக் கவனித்து, அமுல் கூட்டுறவு சங்கத்தின் தற்போதைய பால் விலையை சரிபார்க்கவும். கூடுதல் கடன்களைத் தவிர்க்கவும்.",
  },
  te: {
    "monitoringUnit": "యాక్టివ్ యూనిట్:",
    "villageCluster": "గ్రామ క్లస్టర్:",
    "districtJurisdiction": "జిల్లా పరిధి:",
    "primaryIndustry": "ముఖ్య పరిశ్రమ:",
    "aaConsentApi": "AA సమ్మతి API:",
    "creditConfidenceScore": "క్రెడిట్ నమ్మకం స్కోరు:",
    "liveSyncConsole": "లైవ్ డేటా సింక్ కన్సోల్",
    "verifyPassiveIngestion": "అట్లాస్ మోంగోడిబి లో లైవ్ డేటా సింక్ సరిచూడండి",
    "ingestSmsAlerts": "1. SMS లావాదేవీల అలర్ట్‌లను జోడించండి",
    "ingestSmsHelp": "డేటా సింక్ కోసం SMS ఎంచుకోండి.",
    "pasteSmsPlaceholder": "బ్యాంక్ SMS ఇక్కడ పేస్ట్ చేయండి...",
    "ingestSmsBtn": "SMS నమోదు చేయండి",
    "offlineQueueLedger": "2. ఆఫ్‌లైన్ సింక్ లెడ్జర్",
    "queuedRecords": "క్యూలోని రికార్డులు:",
    "noQueuedOps": "క్యూలో పనులు లేవు. సిస్టమ్ సింక్ అయింది.",
    "forceOfflineSync": "ఆఫ్‌లైన్ సింక్ పునరుద్ధరించు",
    "activeAdvisories": "16 లావాదేవీలు సింక్ • 2 సలహాలు.",
    "dialInCompanion": "వాయిస్ కాల్ అలర్ట్",
    "todaysAiAdvisories": "ఈ రోజు AI సలహా బులెటిన్లు",
    "dynamicallyUpdated": "డైలామిక్ గా అప్‌డేట్ అయింది",
    "simulatedCashPredictions": "అంచనా నగదు ప్రవాహ అంచనాలు (90 రోజులు)",
    "engineView": "ఇంజిన్ వీక్షణ →",
    "whatsDriving": "ఈ అంచనాకు కారణమైన ముఖ్య 3 అంశాలు:",
    "openPassbook": "పాస్‌బుక్ తెరవండి →",
    "expandIndex": "వివరాలు చూడండి →",
    "dateCol": "తేదీ",
    "descCol": "వివరణ",
    "catCol": "వర్గం",
    "amtCol": "మొత్తం",
    "cropCol": "పంట / వస్తువు",
    "rateCol": "ధర",
    "adviceCol": "సలహా",
    "hold": "వేచి ఉండండి (HOLD)",
    "sell": "అమ్మండి (SELL)",
    "buyNow": "ఇప్పుడే కొనండి",
    "buyLater": "తర్వాత కొనండి",
    "rbiSyncTitle": "RBI సమ్మతి డేటా సింక్",
    "smsConsentDesc": "SMS అలర్టులను తనిఖీ చేయండి",
    "upiConsentDesc": "చెల్లింపుల ధృవీకరణ API",
    "imdConsentDesc": "వాతావరణ ప్రభావం గణన",
    "viewFull": "పూర్తిగా చూడండి →",
    "viewFullDebt": "పూర్తి AI రుణ వ్యూహం చూడండి",
    "welcome": "నమస్కారం రమేష్! నేను గ్రామ్‌బాట్ AI, మీ ఆర్థిక సహాయకుడిని. మీ గ్రామం, మీ డైరీ, అమూల్ మరియు వాతావరణం నాకు తెలుసు. ఈ రోజు మీకు ఎలా సహాయపడగలను?",
    "voiceText": "వింటున్నది...",
    "suggest1": "నేను జూలై 26న ట్రాక్టర్ EMI చెల్లించగలనా?",
    "suggest2": "ఈ రోజు నా ఆర్థిక పరిస్థితి పసుపు (Yellow) రంగులో ఎందుకు ఉంది?",
    "suggest3": "సోమవారం నాటి ఎండ తీవ్రత నా పాలు అమ్మకాలపై ఎలాంటి ప్రభావం చూపుతుంది?",
    "suggest4": "పశువుల మేత ఖర్చు 10% పెరిగితే ఏమవుతుంది?",
    "reply1": "అవును, మీరు జూలై 26న ₹7,500 EMI సులభంగా చెల్లించవచ్చు. జూలై 22న అమూల్ నుండి రాబోయే ₹8,200 చెల్లింపుతో మీ వద్ద ₹14,400 ఉంటుంది. మీరు పూర్తిగా సురక్షితంగా ఉన్నారు.",
    "reply2": "ఈ నెలలో మేత ఖర్చులు 15% పెరగడం మరియు సోమవారం ఎండ (37°C) వల్ల పాలు ఉత్పత్తి 12% తగ్గే అవకాశం ఉన్నందున మీ ఆర్థిక స్థితి పసుపు రంగులోకి మారింది. రోజుకు ₹400 ఆదా చేయండి.",
    "reply3": "సోమవారం 37°C వేడి వల్ల పశువులకు వడదెబ్బ తగులుతుంది. దీనివల్ల పాలు ఉత్పత్తి రోజుకు 1.5 నుండి 2 లీటర్లు తగ్గి ₹280 నష్టం రావచ్చు. చల్లని నీరు మరియు బెల్లం ఇవ్వండి.",
    "reply4": "మేత ఖర్చులు 10% పెరిగితే, మీ రోజువారీ ఖర్చులు ₹80 పెరుగుతాయి. మీ నగదు నిల్వలు 45 రోజుల నుండి 38 రోజులకు పడిపోతాయి. దీని కోసం స్థానిక దుకాణాల నుండి రావలసిన ₹1,500 వసూలు చేయండి.",
    "feedback": "ఈ సలహా మీకు అర్థమైందా? (అవును అని చెప్పండి లేదా థంబ్స్ అప్ నొక్కండి)",
    "offlineMsg": "ఆఫ్‌లైన్‌లో నడుస్తోంది. ఇంటర్నెట్ లేకుండా మీ ఫోన్‌లోని లోకల్ మోడల్ ద్వారా సహాయం అందించబడుతుంది.",
    "fallback": "అర్థమైంది. మేత పరిమాణంపై శ్రద్ధ వహించండి మరియు అమూల్ సొసైటీ రేట్లను తనిఖీ చేయండి. ఈ వారం అదనపు అప్పులు తీసుకోకండి.",
    "overviewPanel": "డాష్‌బోర్డ్",
    "passbook": "పాస్‌బుక్",
    "userProfile": "ప్రొఫైల్",
    "debtStrategy": "అప్పు వ్యూహం",
    "governmentSchemes": "ప్రభుత్వ పథకాలు",
    "riskAnalysis": "రిస్క్ విశ్లేషణ",
    "syncStatus": "సింక్ స్థితి",
    "liveSyncApi": "✓ లైవ్ API సింక్",
    "logOutAccount": "సైన్ అవుట్",
    "dataAsOf": "డేటా:",
    "masterSynced": "మాస్టర్ సింక్",
    "sinceLastChecked": "చివరి తనిఖీ తర్వాత",
    "quickActions": "త్వరిత చర్యలు:",
    "logTransaction": "లావాదేవీ నమోదు",
    "viewFullForecast": "అంచనా చూడండి",
    "registerLoanEmi": "రుణం / EMI నమోదు",
    "voiceCompanion": "వాయిస్ సహాయకుడు",
    "financialHealthIndex": "ఆర్థిక ఆరోగ్య సూచిక",
    "predictedCashRunway": "అంచనా నగదు కాలం",
    "outstandingLoansEmi": "బకాయి రుణం EMI",
    "climateThermalStress": "వాతావరణ ఉష్ణ ఒత్తిడి",
    "criticalRisk": "తీవ్ర ప్రమాదం",
    "warningAlert": "హెచ్చరిక",
    "fullySafe": "పూర్తిగా సురక్షితం",
    "safe": "సురక్షితం",
    "danger": "ప్రమాదం",
    "warning": "జాగ్రత్త",
    "daysLeft": "రోజులు",
    "recentAlertsTitle": "ఇటీవలి హెచ్చరికలు",
    "interactivePredictions": "అంచనా",
    "mandiPrices": "మండి ధరలు",
    "weatherIntel": "వాతావరణం",
    "rbiConsent": "RBI అనుమతి",
    "enterpriseDashboard": "వ్యాపార డాష్‌బోర్డ్",
    "debtStrategyTitle": "AI రుణ వ్యూహం",
    "riskAnalysisTitle": "వ్యాపార రిస్క్ విశ్లేషణ",
    "totalMonthlyEmi": "మొత్తం నెలవారీ EMI",
    "refreshAnalysis": "విశ్లేషణ రిఫ్రెష్",
    "registerNewLoan": "🏦 కొత్త రుణం / EMI నమోదు",
    "registerDebtBtn": "రుణం నమోదు",
    "welcomeBack": "స్వాగతం",
    "searchTransactions": "లావాదేవీలు వెతకండి...",
    "debtStrategyDesc": "AI ఆధారిత నగదు-ప్రవాహ మరియు చెల్లింపు ప్రణాళిక.",
    "logManualTxn": "మాన్యువల్ లావాదేవీ",
    "registerBusiness": "వ్యాపారం నమోదు",
    "rbiConsentDashboard": "RBI AA అనుమతి డాష్‌బోర్డ్",
    "revokeAllAccess": "అన్ని యాక్సెస్ రద్దు",
    "exportBankCsv": "బ్యాంక్ CSV డౌన్‌లోడ్",
  },
  kn: {
    "welcome": "ನಮಸ್ಕಾರ ರಮೇಶ್! ನಾನು ಗ್ರಾಮ್‌ಬಾಟ್ AI, ನಿಮ್ಮ ಆರ್ಥಿಕ ಸಹಾಯಕ. ನಿಮ್ಮ ಗ್ರಾಮ, ಡೈರಿ ಫಾರ್ಮ್, ಅಮುಲ್ ಮತ್ತು ಹವಾಮಾನದ ಬಗ್ಗೆ ನನಗೆ ತಿಳಿದಿದೆ. ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
    "voiceText": "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...",
    "suggest1": "ನಾನು ಜುಲೈ 26 ರಂದು ಟ್ರ್ಯಾಕ್ಟರ್ ಇಎಂಐ ಪಾವತಿಸಬಹುದೇ?",
    "suggest2": "ಇಂದು ನನ್ನ ಆರ್ಥಿಕ ಪರಿಸ್ಥಿತಿ ಹಳದಿ (Yellow) ಬಣ್ಣದಲ್ಲಿ ಏಕಿದೆ?",
    "suggest3": "ಸೋಮವಾರದ ಬಿಸಿಗಾಳಿ ನನ್ನ ಹಾಲು ಮಾರಾಟದ ಮೇಲೆ ಹೇಗೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ?",
    "suggest4": "ಮೇವು ವೆಚ್ಚ ಶೇಕಡಾ 10 ರಷ್ಟು ಹೆಚ್ಚಾದರೆ ಏನಾಗುತ್ತದೆ?",
    "reply1": "ಹೌದು, ಜುಲೈ 26 ರಂದು ₹7,500 ಇಎಂಐ ಅನ್ನು ನೀವು ಸುಲಭವಾಗಿ ಪಾವತಿಸಬಹುದು. ಜುಲೈ 22 ರಂದು ಅಮುಲ್‌ನಿಂದ ಬರಲಿರುವ ₹8,200 ಪಾವತಿಯ ನಂತರ ನಿಮ್ಮ ಬಳಿ ₹14,400 ಇರುತ್ತದೆ. ನೀವು ಸಂಪೂರ್ಣ ಸುರಕ್ಷಿತರಾಗಿದ್ದೀರಿ.",
    "reply2": "ಈ ತಿಂಗಳು ಮೇವಿನ ವೆಚ್ಚ 15% ಹೆಚ್ಚಿರುವುದರಿಂದ ಮತ್ತು ಸೋಮವಾರದ ಬಿಸಿಲಿನಿಂದ (37°C) ಹಾಲಿನ ಉತ್ಪಾದನೆ 12% ಕುಸಿಯುವ ಸಾಧ್ಯತೆಯಿರುವುದರಿಂದ ನಿಮ್ಮ ಸ್ಥಿತಿ ಹಳದಿಯಾಗಿದೆ. ದಿನಕ್ಕೆ ₹400 ಉಳಿಸಿ.",
    "reply3": "ಸೋಮವಾರ 37°C ತಾಪಮಾನವು ಜಾನುವಾರುಗಳಿಗೆ ತೊಂದರೆ ನೀಡುತ್ತದೆ. ಇದರಿಂದ ದಿನಕ್ಕೆ ಹಾಲಿನ ಉತ್ಪಾದನೆ 1.5 ರಿಂದ 2 ಲೀಟರ್ ಕುಸಿದು ₹280 ನಷ್ಟವಾಗಬಹುದು. ತಂಪಾದ ನೀರು ಮತ್ತು ಬೆಲ್ಲ ನೀಡಿ.",
    "reply4": "ಮೇವು ವೆಚ್ಚ 10% ಹೆಚ್ಚಾದರೆ ದಿನದ ಖರ್ಚು ₹80 ಹೆಚ್ಚುತ್ತದೆ. ನಿಮ್ಮ ನಗದು ಬ್ಯಾಕಪ್ 45 ದಿನಗಳಿಂದ 38 ದಿನಗಳಿಗೆ ಕುಸಿಯುತ್ತದೆ. ಸಮತೋಲನಕ್ಕಾಗಿ ಸ್ಥಳীয় ಅಂಗಡಿಯಿಂದ ಬರಬೇಕಾದ ₹1,500 ವಸೂಲಿ ಮಾಡಿ.",
    "feedback": "ಈ ಸಲಹೆ ನಿಮಗೆ ಅರ್ಥವಾಗಿದೆಯೇ? (ಹೌದು ಎಂದು ಹೇಳಿ ಅಥವಾ ಲೈಕ್ ಬಟನ್ ಒತ್ತಿ)",
    "offlineMsg": "ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ. ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆ ನೇರವಾಗಿ ನಿಮ್ಮ ಫೋನ್‌ನ ಲೋಕಲ್ ಮಾಡೆಲ್ ಮೂಲಕ ಸಲಹೆ ನೀಡಲಾಗುತ್ತಿದೆ.",
    "fallback": "ಅರ್ಥವಾಯಿತು. ಮೇವಿನ ಪ್ರಮಾಣವನ್ನು ಗಮನಿಸಿ ಮತ್ತು ಹತ್ತಿರದ ಅಮುಲ್ ಕೇಂದ್ರದ ದರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ. ಈ ವಾರ ಸಾಲ ಪಡೆಯುವುದನ್ನು ತಪ್ಪಿಸಿ.",
  },
  ml: {
    "welcome": "നമസ്കാരം രമേഷ്! ഞാൻ ഗ്രാംബോട്ട് AI, നിങ്ങളുടെ സാമ്പത്തിക സഹായി. നിങ്ങളുടെ ഗ്രാമം, ഡയറി ഫാം, അമുൽ, കാലാവസ്ഥ എന്നിവ എനിക്കറിയാം. ഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കണം?",
    "voiceText": "ശ്രദ്ധിക്കുന്നു...",
    "suggest1": "എനിക്ക് ജൂലൈ 26-ന് ട്രാക്ടർ ഇഎംഐ അടയ്ക്കാൻ കഴിയുമോ?",
    "suggest2": "ഇന്ന് എന്റെ സാമ്പത്തിക നില എന്തുകൊണ്ട് മഞ്ഞ (Yellow) നിറത്തിലാണ്?",
    "suggest3": "തിങ്കളാഴ്ചത്തെ ചൂട് എന്റെ പാൽ വിൽപ്പനയെ എങ്ങനെ ബാധിക്കും?",
    "suggest4": "തീറ്റച്ചെലവ് 10% വർദ്ധിച്ചാൽ എന്താണ് സംഭവിക്കുക?",
    "reply1": "അതെ, ജൂലൈ 26 ന് ₹7,500 ഇഎംഐ നിങ്ങൾക്ക് എളുപ്പത്തിൽ അടയ്ക്കാം. ജൂലൈ 22 ന് അമുലിൽ നിന്ന് ലഭിക്കുന്ന ₹8,200 പേയ്‌മെന്റിന് ശേഷം നിങ്ങളുടെ പക്കൽ ₹14,400 ഉണ്ടാകും. നിങ്ങൾ പൂർണ്ണമായും സുരക്ഷിതനാണ്.",
    "reply2": "ഈ മാസം തീറ്റച്ചെലവ് 15% വർദ്ധിച്ചതിനാലും തിങ്കളാഴ്ചത്തെ ഉയർന്ന ചൂട് (37°C) കാരണം പാൽ ഉത്പാദനം 12% കുറയാൻ സാധ്യതയുള്ളതിനാലും നിങ്ങളുടെ നില മഞ്ഞയാണ്. ദിവസവും ₹400 സമ്പാദിക്കുക.",
    "reply4": "തീറ്റവില 10% ഉയർന്നാൽ പ്രതിദിന ചെലവ് ₹80 വർദ്ധിക്കും. നിങ്ങളുടെ പണ ബാക്കപ്പ് 45 ദിവസത്തിൽ നിന്ന് 38 ദിവസമായി കുറയും. ഇതിനായി പ്രാദേശിക കടയിൽ നിന്നുള്ള ₹1,500 കുടിശ്ശിക ഉടൻ ഈടാക്കുക.",
    "feedback": "ഈ ഉപദേശം മനസ്സിലായോ? (അതെ എന്ന് പറയുക അല്ലെങ്കിൽ തംസ് അപ് ചെയ്യുക)",
    "offlineMsg": "ഓഫ്‌ലൈനിൽ പ്രവർത്തിക്കുന്നു. ഇന്റർനെറ്റ് ഇല്ലാതെ ഫോണിലെ ലോക്കൽ മോഡൽ വഴി സഹായം നൽകുന്നു.",
    "fallback": "മനസ്സിലായി. കന്നുകാലി തീറ്റയുടെ അളവ് ശ്രദ്ധിക്കുകയും അമുൽ സൊസൈറ്റി നിരക്കുകൾ പരിശോധിക്കുകയും ചെയ്യുക. ഈ ആഴ്ച പുതിയ കടം ഒഴിവാക്കുക.",
  },
};

export const DASHBOARD_TRANSLATIONS = CHATBOT_TRANSLATIONS;
